export enum KYC_STATUS {
  'REGISTERED' = 'REGISTERED',
  'SUBMITTED' = 'SUBMITTED',
  'CONFIRMED' = 'CONFIRMED',
  'VALIDATED' = 'VALIDATED',
  'QUARANTINED' = 'QUARANTINED',
  'BANNED' = 'BANNED',
  'REVIEWED' = 'REVIEWED'
}